[package]
name = "test_wasm_x_salsa20_poly1305"
version = "0.0.1"
authors = [ "Carlos Tovar", "carlos.tovar@blockinnovation.center" ]
edition = "2018"

[lib]
name = "test_wasm_x_salsa20_poly1305"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
hdk = { path = "../../../../hdk" }
serde = "=1.0.104"
