[package]
name = "test_wasm_ser_regression"
version = "0.0.1"
authors = [ "Carlos Tovar", "carlos.tovar@blockinnovation.center" ]
edition = "2018"

[lib]
name = "test_wasm_ser_regression"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
serde = "1.0.104"
hdk = { path = "../../../../hdk" }
derive_more = "0.99.11"
