ARG DOCKER_BRANCH=develop
FROM aingle/aingle:latest.${DOCKER_BRANCH}

RUN `nix-build . --no-link -A pkgs.ci.ciSetupNixConf`/bin/ai-ci-setup-nix-conf.sh
RUN nix-shell --pure --argstr flavor coreDev --run ai-merge-test
