[package]
name = "aingle_websocket"
version = "0.0.1"
description = "AIngle utilities for serving and connection with websockets"
license = "Apache-2.0"
homepage = "https://github.com/Daironode/aingle"
documentation = "https://github.com/Daironode/aingle"
authors = [ "AIngle Core Dev Team <devcore@aingle.ai>" ]
edition = "2018"

[dependencies]
futures = "0.3"
<<<<<<< HEAD
aingle_middleware_bytes = "=0.0.3"
=======
aingle_serialized_bytes = "=0.0.48"
>>>>>>> master
nanoid = "0.3"
net2 = "0.2"
serde = { version = "1", features = [ "derive" ] }
serde_bytes = "0.11"
tokio = { version = "0.2", features = [ "full" ] }
tokio-tungstenite = { version = "0.10.1", features = [ "tls" ] }
tracing = "0.1"
tracing-futures = "0.2"
tungstenite = "0.10"
url2 = "0.0.6"

[dev-dependencies]
aingle_types = { version = "=0.0.1", path = "../aingle_types" }
linefeed = "0.6"
observability = "0.1.3"
