[package]
name = "aingle"
<<<<<<< HEAD
version = "0.0.1"
=======
version = "0.0.100"
>>>>>>> master
description = "AIngle, a framework for distributed applications"
license = "CAL-1.0"
homepage = "https://github.com/Daironode/aingle"
documentation = "https://github.com/Daironode/aingle"
authors = [ "AIngle Core Dev Team <devcore@aingle.ai>" ]
edition = "2018"

[dependencies]
anyhow = "1.0.26"
async-trait = "0.1"
base64 = "0.13"
byteorder = "1.3.4"
cfg-if = "0.1"
chrono = "0.4.6"
derivative = "2.1.1"
derive_more = "0.99.3"
directories = "2.0.2"
either = "1.5.0"
fallible-iterator = "0.2.0"
fixt = { version = "0.0.1", path = "../fixt" }
futures = "0.3.1"
ghost_actor = "0.3.0-alpha.1"
aingle_hash = { version = "0.0.1", path = "../aingle_hash", features = ["full"] }
aingle_cascade = { version = "0.0.1", path = "../aingle_cascade" }
aingle_conductor_api = { version = "0.0.1", path = "../aingle_conductor_api" }
aingle_keystore = { version = "0.0.1", path = "../aingle_keystore" }
aingle_p2p = { version = "0.0.1", path = "../aingle_p2p" }
aingle_lmdb = { version = "0.0.1", path = "../aingle_lmdb" }
<<<<<<< HEAD
aingle_middleware_bytes = "=0.0.3"
aingle_state = { version = "0.0.1", path = "../aingle_state" }
aingle_types = { version = "0.0.1", path = "../aingle_types" }
aingle_wasm_test_utils = { version = "0.0.1", path = "../test_utils/wasm" }
aingle_wasmer_host = "=0.0.1"
=======
aingle_serialized_bytes = "=0.0.48"
aingle_state = { version = "0.0.1", path = "../aingle_state" }
aingle_types = { version = "0.0.1", path = "../aingle_types" }
aingle_wasm_test_utils = { version = "0.0.1", path = "../test_utils/wasm" }
aingle_wasmer_host = "=0.0.66"
>>>>>>> master
aingle_websocket = { version = "0.0.1", path = "../aingle_websocket" }
aingle_zome_types = { version = "0.0.1", path = "../aingle_zome_types" }
human-panic = "1.0.3"
lazy_static = "1.4.0"
mockall = "0.8"
must_future = "0.1.1"
nanoid = "0.3"
num_cpus = "1.8"
observability = "0.1.3"
parking_lot = "0.10"
predicates = "1.0.4"
rand = "0.7"
ring = "0.16"
<<<<<<< HEAD
serde = { version = "1.0.123", features = [ "derive" ] }
=======
serde = { version = "1.0.104", features = [ "derive" ] }
>>>>>>> master
serde_json = { version = "1.0.51", features = [ "preserve_order" ] }
serde_yaml = "0.8"
shrinkwraprs = "0.3.0"
structopt = "0.3.11"
strum = "0.18.0"
tempdir = "0.3.7"
thiserror = "1.0.22"
tokio = { version = "0.2.11", features = [ "full" ] }
tokio_safe_block_on = "0.1.2"
toml = "0.5.6"
tracing = "=0.1.21"
tracing-futures = "0.2.4"
tracing-subscriber = "0.2.15"
url = "1.7.2"
url2 = "0.0.6"
url_serde = "0.2.0"
uuid = { version = "0.7", features = [ "serde", "v4" ] }
kitsune_p2p = { version = "0.0.1", path = "../kitsune_p2p/kitsune_p2p" }
xsalsa20poly1305 = "0.6.0"
once_cell = "1.4.1"

# Dependencies for test_utils: keep in sync with below
hdk = { path = "../hdk", optional = true }
matches = {version = "0.1.8", optional = true }
aingle_test_wasm_common = { version = "0.0.1", path = "../test_utils/wasm_common", optional = true  }
unwrap_to = { version = "0.1.0", optional = true }
itertools = { version = "0.9", optional = true }


[dev-dependencies]
anyhow = "1.0.26"
assert_cmd = "1.0.1"
criterion = "0.3"
maplit = "1"
pretty_assertions = "0.6.1"
serial_test = "0.4.0"
test-case = "1.0.0"

# Dependencies for test_utils: keep in sync with above
hdk = { path = "../hdk", optional = false }
matches = {version = "0.1.8", optional = false }
aingle_test_wasm_common = { version = "0.0.1", path = "../test_utils/wasm_common", optional = false  }
unwrap_to = { version = "0.1.0", optional = false }


[[bench]]
name = "bench"
harness = false

[lib]
name = "aingle"
path = "src/lib.rs"

[[bin]]
name = "aingle"
path = "src/bin/aingle/main.rs"

[features]
default = ["slow_tests", "test_utils", "only_check_wasms"]

# Exposes additional functionality only needed for integration tests.
# This feature should be turned off for production builds.
test_utils = [
  "hdk",
  "aingle_lmdb/test_utils",
  "aingle_state/test_utils",
  "aingle_types/test_utils",
  "aingle_zome_types/test_utils",
  "itertools",
  "matches",
  "aingle_test_wasm_common",
  "unwrap_to"
]

# Wasm ribosome tests take > 60 seconds - let's only run them in CI
slow_tests = []

# Includes the wasm build script, which we don't need when not building wasms
build_wasms = ['aingle_wasm_test_utils/build']
only_check_wasms = ['aingle_wasm_test_utils/only_check']
