[package]
name = "aingle_test_wasm_common"
version = "0.0.1"
authors = [ "Carlos Tovar", "carlos.tovar@blockinnovation.center" ]
edition = "2018"

[lib]
name = "aingle_test_wasm_common"
crate-type = [ "cdylib", "rlib" ]
path = "src/lib.rs"

[dependencies]
<<<<<<< HEAD
aingle_middleware_bytes = "=0.0.3"
serde = "=1.0.123"
=======
aingle_serialized_bytes = "=0.0.48"
serde = "=1.0.104"
>>>>>>> master
serde_bytes = "0.11"
hdk = { path = "../../hdk" }
