[package]
name = "test_wasm_query"
version = "0.0.1"
authors = [ "thedavidmeister", "thedavidmeister@gmail.com" ]
edition = "2018"

[lib]
name = "test_wasm_query"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
adk = { path = "../../../../adk", features = [] }
serde = "1.0"
aingle_test_wasm_common = { version = "=0.0.1", path = "../../../wasm_common" }

[features]
default = []
mock = ["adk/mock"]