[package]
name = "test_wasm_debug"
version = "0.0.1"
authors = [ "Carlos Tovar", "carlos.tovar@blockinnovation.center" ]
edition = "2018"

[lib]
name = "test_wasm_debug"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
hdk = { path = "../../../../hdk" }
serde = "=1.0.104"
tracing = "0.1"
tracing-core = "0.1"
tracing-subscriber = "0.2"